@startuml
left to right direction
rectangle "Nodes" {
  node (MySheet)
  node (MyText)
  node (A) as " " #black
  (MySheet) -- (A)
  (A) --> (MyText)
}
rectangle "Meta" {
  node (Sheet)
  node (Text)
  node (Contains)
  (MySheet) -[#red]-> (Sheet)
  (MyText) -[#red]-> (Text)
  (A) .> (Contains)
  node (B) as " " #black
  (Contains) -u- (B)
  (B) -u-> (Sheet)
  node (C) as " " #black
  (Contains) -d- (C)
  (C) -d-> (Text)
}
rectangle "RelationsMeta" {
  node (sourceType)
  node (targetType)
  node (edge2Node)
  (sourceType) -[#blue]-> (edge2Node)
  (targetType) -[#blue]-> (edge2Node)
  (B) .d-> sourceType
  (C) .d-> targetType
  node (E) as " " #black
  node (F) as " " #black
  (E) .l-> sourceType
  (F) .l-> targetType
  (edge2Node) - (E)
  (edge2Node) - (F)
}
rectangle "MetaMeta" {
  node (nodeTypeNode)
  node (edgeTypeNode)
  (E) -> (edgeTypeNode)
  (F) -> (nodeTypeNode)
  (nodeTypeNode) -[hidden]d-> (edgeTypeNode)
  (Text) -r[#red]-> (nodeTypeNode)
  (Sheet) -r[#red]-> (nodeTypeNode)
  (Contains) -[#red]u-> (edgeTypeNode)
  (sourceType) -[#red]-> (edgeTypeNode)
  (targetType) -[#red]-> (edgeTypeNode)
  (edge2Node) -[#red]-> (edgeTypeNode)
}
(Nodes) -[hidden]r- (Meta)
(Meta) -[hidden]r- (MetaMeta)
(MetaMeta) -[hidden]r- (MetaMetaMeta)
rectangle "MetaMetaMeta" {
  (nodeTypeNode) -[#red]-> (typeNodeTypeNode)
  (edgeTypeNode) -[#red]-> (typeNodeTypeNode)
  (typeNodeTypeNode) -[#red]-> (typeNodeTypeNode)
}
legend right
  <color:#red>——→</color> type
  <color:#blue>——→</color> sub-class
endlegend
@enduml
